spring.application.name=TableManagementApplication

## Configuration to connect PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/table_management_db
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## Default seeded user credentials (change these in production!)
app.init.admin-username=admin
app.init.admin-password=admin@123
app.init.staff-username=staff
app.init.staff-password=staff@123